pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/ragulak-2/Jenkins-website1.git'
        BRANCH = 'main'
        DEPLOY_DIR = '/var/www/html'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: "${BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('Build') {
            steps {
                echo "No build required for static website"
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh """
                sudo rm -rf ${DEPLOY_DIR}/*
                sudo cp -r * ${DEPLOY_DIR}/
                """
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Build Failed!'
        }
    }
}
